### PR TITLE
feat: inverse modifier

### PR DESCRIPTION
**Pull request by enzonotario**
Hi Henry, hope you're doing well!

I also want to have the chalk's `inverse` modifier, so I went through it. Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by henryhale** [comment]
Hello Enzo,

Thank you very much for checking out this package.  

I believe that it is a cool feature. It should be added as soon as possible.

I have went through it and I kindly suggest that you make the following changes too;

- Add the modifier: `inverse` in the modifier's section of the `README.md` file
- Edit the declaration file `index.d.ts`: add the inverse modifier in the `Chalk` interface.
- Create a separate test block for the modifier
  The test for this modifier is falling under `Multiple arguments` section.

  Screenshot from 2023-07-09 17-20-49

  Solution:
  ```js
  ...

  log('\nInverse Colors');

  test('inverse colors', t => {
      t.equal(p.bgWhite.black.inverse('inverse', 'colors'), '<span style="background-color:#000000;color:#FFFFFF;">inverse colors</span>');
  });

  ...
  ```

**Comment by henryhale** [comment]
Chalk-dom v1.1.0 will be released thereafter.

Thank you again.

**Comment by enzonotario** [comment]
Hi Henry, nice!

I've resolved those things. Also I've moved `inverse` test to `modifier` section. I don't think it need a dedicated section, since its just another modifier. Let me know what you think.

Thanks!

**Comment by henryhale** [comment]
That's great! I should say that you are right about the `inverse` modifier.

Thank you very much.

**Comment by enzonotario** [comment]
Nice! Thank you so much!

**Pull request merged**
